### PR TITLE
Resolving Xcode 6.3 warnings regarding auto property synthesis of proper...

### PR DESCRIPTION
**Pull request by kendomke**
...ties implemented by a superclass.

Minor: Updates to address Xcode 6.3 warnings

### CODE REVIEW

**Comment by kendomke** [comment]
@gpambrozio to review

**Comment by gpambrozio** [comment]
The right thing to do here is to actually remove the duplicated property declarations on these files as the one in the superclass is public anyway.

**Comment by kendomke** [comment]
Changed by removing duplicated declarations.  Please re-review.

**Comment by gpambrozio** [comment]
lgtm

**Pull request merged**
